[package]
name = "svd-compare"
version = "0.1.0"
authors = ["Andrey Zgarbul"]
edition = "2021"

[dependencies]
svd-parser = "0.14.4"
svd-encoder = "0.14.4"
svd-rs = { version = "0.14.6", features = ["serde"] }
serde_yaml = "0.8.26"
md5 = "0.7.0"
clap = { version = "4.4.11", features = ["derive"] }
